### PR TITLE
Migrate Structopt to clap

### LINKED ISSUE #89: migrate to clap
given the [structopt](https://github.com/TeXitoi/structopt) library is in maintenance mode and itself suggests to make the [migration](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating-1)

### PR DESCRIPTION
**Pull request by king-11**
fixes #89

### CODE REVIEW

**Comment by dpc** [comment]
:clap: (sorry, couldn't help myself). LGTM :D

**Comment by king-11** [comment]
I didn't quite get what was the sorry for 🫠 but thanks for quick review 😃

**Comment by dpc** [comment]
`:clap:`, pun intended

**Comment by king-11** [comment]
😂 okay got it now 👏🏻

**Comment by RCasatta** [comment]
Concept ack

There is a format error, and an examples to be fixed to make the CI happy

**Comment by king-11** [comment]
fixed the example and formatting too

**Comment by king-11** [comment]
@RCasatta can you run the workflow now 😅

**Review by RCasatta — APPROVED** [review]
LGTM! Thanks a lot!

Sorry for the delay of the last review, I missed the changes, feel free to ping me if it happens!

**Comment by king-11** [comment]
sure no worries just glab I could contribute will work on the crate separation part now :)

**Pull request merged**
