### PR TITLE
Opt avoid timestamp

### PR DESCRIPTION
**Pull request by RCasatta**

### CODE REVIEW

**Comment by dpc** [comment]
@RCasatta BTW. If you're using env_logger, you should be aware of https://github.com/rust-cli/env_logger/issues/123 , maybe you want to disable `regex` cargo feature on it.

**Comment by RCasatta** [comment]
oh didn't know... Thanks for the info

**Comment by RCasatta** [comment]
I don't see `log` in perf reports of a another project of mine. I disabled `regex` feature of `env_logger` and didn't notice perf difference before/after

image

**Comment by dpc** [comment]
Did you set the `RUST_LOG` to anything? It kicks in only after it's actually filtering. Also - if you don't happen to have any heavy `trace`s etc in hot loops in your deps, it might actually not be a problem.

**Comment by RCasatta** [comment]
`RUST_LOG` is unset, but internally I have 
`let mut builder = env_logger::Builder::from_env(Env::default().default_filter_or("info"));`

So I supposed it could have been affected, but it seems not.

**Pull request merged**
